### ISSUE TITLE
TooltipLabel is also used without a tooltip, so actually the component name is wrong

### ISSUE THREAD

**Issue by lowiebenoot** [teamleadercrm/ui#173]
The `TooltipLabel` component is also used without a tooltip, so actually the component name is wrong.
For example in invoicing it's also used as a link.

<img width="531" alt="screen shot 2018-01-02 at 17 30 04" src="https://user-images.githubusercontent.com/330765/34491144-97400760-efe2-11e7-9016-70f4ee964885.png">

**Comment by driesd** [comment]
Solved in #177
