### ISSUE TITLE
Input number field: increase/decrease value combined with shift key

### ISSUE THREAD

**Issue by driesd** [teamleadercrm/ui#216]
### Expected behavior
Can use `Shift key` to increase/decrease the number input value by 10 (or step * 10) instead of by the defined step value.

### Actual behavior
Input number value can only be increased/decreased by the defined `step` value.

**Comment by Kemosabert** [comment]
fixed in P

**Comment by LennertBlommaert** [comment]
Closing this, as we do not have this in the design specs for now.
