### ISSUE TITLE
Numpad number keys 6, 7, 8 and 9 will increment the value by 0.01

### ISSUE THREAD

**Issue by driesd** [teamleadercrm/ui#217]
### Expected behavior
Pressing these keys should not result in stepping beyond the maximum value.

### Actual behavior
Numpad number keys 6, 7, 8 and 9 will increment the value by 0.01, even if it has reached the maximum value.

### Steps to reproduce actual behavior
1. Step to maximum value
2. Use numpad keys 6, 7, 8 and 9 to increase beyond the maximum with a step of 0.01.

**Comment by Kemosabert** [comment]
This issue has been resolved in the above PR.
