### ISSUE TITLE
Track IE11 issue in DayPicker

### ISSUE THREAD

**Issue by nickwaelkens** [teamleadercrm/ui#227]
We are using `react-day-picker`; the current version has an issue in IE11. Let's make sure, by the time our day picker wrapper is finished, this bug is also fixed.

See https://github.com/gpbl/react-day-picker/issues/668

**Comment by driesd** [comment]
This is fixed in v7.1.8. I updated the package in [this commit](https://github.com/teamleadercrm/ui/pull/226/commits/2f93dfbd3db2b673fa036fdac372bba0f563a26b).
