### ISSUE TITLE
Unexpected behaviour input

### ISSUE THREAD

**Issue by InstaK** [teamleadercrm/ui#229]
When using the Input component and adding a function to it, e.g.
```js
  <Input input={{onChange: this.handleChange}}/>
```
### Expected behavior
The parameter `event` in the `handleChange` function to be your event
### Actual behavior
The parameter `event` in the `handleChange` function is your event.target.value

Upon fixing this needs to be changed in `client/src/application/SupportPermissionRequest/SupportPermissionRequest.js`

**Comment by Kemosabert** [comment]
Fixed in PR #289
