### ISSUE TITLE
Text of error and icon are not aligned

### ISSUE THREAD

**Issue by InstaK** [teamleadercrm/ui#231]
### Expected behavior
Alignment of error text and its icon

### Actual behavior
Not aligned

### Solution:
```css
display: flex;
align-items: center;
```
on the container div of error icon and error text

### Screenshot of when the issue occures
before:
https://puu.sh/zNcxJ/68538efcba.png
after:
https://puu.sh/zNcyk/2ffa4a9351.png

**Comment by driesd** [comment]
@InstaK Which component are we talking about here?

**Comment by InstaK** [comment]
Oh sorry, it's the Input component.

**Comment by Kemosabert** [comment]
Issue resolved with merging PR #291
