### ISSUE TITLE
Using toasts with animation isn't very flexible.

### ISSUE THREAD

**Issue by lowiebenoot** [teamleadercrm/ui#288]
### Expected behaviour
If you add a toast, it should always animate.

### Actual behaviour
We first need to add a toast, with the prop `active = false`. If you then change the `active` prop to `true`, it will become visible with an animation.

This isn't a very flexible way to use toasts. You'll probably never render a toast, without wanting it to  be visible. So the `active` prop is kind of useless actually, and it should just animate as soon as it enters/exits the DOM.

You might fix this together with the stacking of toats, and add some fancy animations in there.

**Comment by Kemosabert** [comment]
Fixed in PR #298. The active prop is no longer needed and animations will be more consistent
