### ISSUE TITLE
Button with Icon or IconButton?

### ISSUE THREAD

**Issue by InstaK** [teamleadercrm/ui#302]
To discuss:

- A Button, by default, has a font-size of 14px, when adding an Icon as a child in there the Icon also gets that font size resulting in a differently positioned Icon.

Possible solutions: 
- Look for the fitting font-size on the button to fit the Icon correctly (not preferred)
- Check if an svg or img is passed to Button so it doesn't get a font-size (more preferred)
- Get support for backgrounds (or levels) on IconButtons (preferred)

**Comment by LennertBlommaert** [comment]
We're currently looking if we can merge the different buttons as these components apart from their styling, don't differ that much. Putting this on hold in the meantime.

**Comment by LennertBlommaert** [comment]
When looking back at this, it doesn't seems like a valid issue to me.
As icons in the `Button` component should be passed to the `icon` prop and not as a child.

So I'm closing this, feel free to reopen if needed.

**Comment by InstaK** [comment]
This is the case @LennertBlommaert 	
![image](https://user-images.githubusercontent.com/9056632/47492440-4b2b2400-d84d-11e8-99bf-fba2d662aee8.png)

so IMO this is still an issue...

**Comment by InstaK** [comment]
Although I must say, the `+` icon is correctly aligned right now in the contextualAddMenu for some mysterious reason... So something must've changed which resolved it, but it seems to be okay now. Still think a font-size shouldn't be added to a button which only contains an icon 😬
