### ISSUE TITLE
DataGrid has medium-sized checkboxes when selectable

### ISSUE THREAD

**Issue by InstaK** [teamleadercrm/ui#306]
### Expected behavior
DataGrid to have small-sized checkboxes by default (maybe the option to change it?) when selectable

### Actual behavior
DataGrid has medium-sized checkboxes when selectable

### Screenshot of when the issue occures
Currently:
![screen shot 2018-07-03 at 15 28 09](https://user-images.githubusercontent.com/9056632/42222511-b7b00bbc-7ed5-11e8-8831-f308855cab42.jpg)

Should be:
![screen shot 2018-07-03 at 15 27 42](https://user-images.githubusercontent.com/9056632/42222497-adee3e00-7ed5-11e8-87a1-7feb63568772.jpg)

**Comment by Kemosabert** [comment]
fixed with pr #310
