### ISSUE TITLE
selectedRows of DataGrid temporarily is undefined

### ISSUE THREAD

**Issue by InstaK** [teamleadercrm/ui#316]
### Expected behavior

selectedRows to initially always be an empty array

### Actual behavior

selectedRows is undefined

### Screenshot of when the issue occures

![image](https://user-images.githubusercontent.com/9056632/43136657-bacc63b6-8f49-11e8-9757-fbcf38b598b7.png)

**Comment by Kemosabert** [comment]
Fixed with PR #318
